# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movie6CodingTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Movie6CodingTest
  pod 'XCDYouTubeKit', '~> 2.5'

  target 'Movie6CodingTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Movie6CodingTest-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Movie6CodingTest-tvOS

  target 'Movie6CodingTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
